### PR TITLE
Changes mediaTypes ordering

### LINKED ISSUE #90: IMS responds with octet-stream when image/jpeg is available
I'm currently working with a Slim deployment which is retrieving JPEG encoded SM instances. The request's accept header is as follows:

`multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50`

and the response's `content type` is:
`multipart/related;start="<***@resteasy-multipart>";type="application/octet-stream"; boundary***`

The source image is JPEG encoded, so I think that since JPEG appears after octet-stream, it chooses octet-stream instead. I assume the issue is introduced here:
https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/097282b5690886735f3fe6521d0774ee33b7f418/src/pyramid.js#L461-L472

Would it be sufficient to just put push the octet stream mediatype after the jpeg mediatype if statement?

### PR DESCRIPTION
**Pull request by cgorman**
Moved octet-stream to the bottom of the mediaTypes list

Closes #90

### CODE REVIEW

**Comment by cgorman** [comment]
> If I remember correctly, the suggested order caused problems with some archives. With which archives have you tested it?

Just with DCM4CHEE. Is there maybe another way to handle the bug if that is an issue?

**Comment by hackermd** [comment]
> > If I remember correctly, the suggested order caused problems with some archives. With which archives have you tested it?
> 
> Just with DCM4CHEE. Is there maybe another way to handle the bug if that is an issue?

I suggest consulting with @gunterze, who maintains DCM4CHEE and may be able to provide further insight.

**Comment by hackermd** [comment]
@cgorman we should definitely make sure that this change will work with the Google Healthcare API to ensure it won't break the IDC viewer.

**Comment by cgorman** [comment]
@hackermd per discussion in the issue thread, I've updated the octet-stream mediatype to have a q-value weight of 0.5. Since this is just a part of the HTTP standard I don't imagine it will introduce issues, but let me know if you have any issues.

**Comment by cgorman** [comment]
Ok changing this to draft until we figure out exactly what to do. I tested locally and while the q parameter doesn't break anything, it also doesn't fix the issue.

**Comment by cgorman** [comment]
Got ahead of myself, adding the q parameter makes more sense in the dicomweb-client library

**Comment by gunterze** [comment]
Testing dcm4chee-arc 5.29.2 with curl:

```
.> accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*; q=0.5, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50
```
returns
```
< Content-Type: multipart/related;start="<cb06884a-88a0-48f6-8f63-2706415dc144@resteasy-multipart>";type="application/octet-stream"; boundary=85ea7b99-ef24-4b74-89cf-b248ed3910a1
```
$ curl -H 'accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50' -vO http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/2.16.840.1.113995.3.110.3.0.10118.6000009.497166.721604/series/2.16.840.1.113995.3.110.3.0.10118.6000009.258169/instances/2.16.840.1.113995.3.110.3.0.10118.6000009.258169.1
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/2.16.840.1.113995.3.110.3.0.10118.6000009.497166.721604/series/2.16.840.1.113995.3.110.3.0.10118.6000009.258169/instances/2.16.840.1.113995.3.110.3.0.10118.6000009.258169.1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: origin, content-type, accept, authorization
< Access-Control-Expose-Headers: content-type, warning
< Date: Mon, 13 Mar 2023 19:56:51 GMT
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< ETag: "-595173981"
< Last-Modified: Mon, 13 Mar 2023 19:50:38 GMT
< Access-Control-Allow-Credentials: true
< Transfer-Encoding: chunked
< Content-Type: multipart/related;start="<cb06884a-88a0-48f6-8f63-2706415dc144@resteasy-multipart>";type="application/octet-stream"; boundary=85ea7b99-ef24-4b74-89cf-b248ed3910a1
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
< 
{ [38837 bytes data]
* Connection #0 to host localhost left intact
```

but adding `; q=0.5`
```
.> accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*; q=0.5, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50
```
returns
```
< Content-Type: multipart/related;start="<373c724d-9bcb-4587-985e-b8e564722765@resteasy-multipart>";transfer-syntax=1.2.840.10008.1.2.4.50;type="image/jpeg"; boundary=ee2160ef-4ed3-4ca2-879d-1acb1b0def0a
```

```
$ curl -H 'accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*; q=0.5, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50' -vO http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/2.16.840.1.113995.3.110.3.0.10118.6000009.497166.721604/series/2.16.840.1.113995.3.110.3.0.10118.6000009.258169/instances/2.16.840.1.113995.3.110.3.0.10118.6000009.258169.1
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/2.16.840.1.113995.3.110.3.0.10118.6000009.497166.721604/series/2.16.840.1.113995.3.110.3.0.10118.6000009.258169/instances/2.16.840.1.113995.3.110.3.0.10118.6000009.258169.1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> accept: multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.80, multipart/related; type="image/jls"; transfer-syntax=1.2.840.10008.1.2.4.81, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.90, multipart/related; type="image/jp2"; transfer-syntax=1.2.840.10008.1.2.4.91, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.92, multipart/related; type="image/jpx"; transfer-syntax=1.2.840.10008.1.2.4.93, multipart/related; type="application/octet-stream"; transfer-syntax=*; q=0.5, multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: origin, content-type, accept, authorization
< Access-Control-Expose-Headers: content-type, warning
< Date: Mon, 13 Mar 2023 19:59:17 GMT
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< ETag: "-595173981"
< Last-Modified: Mon, 13 Mar 2023 19:50:38 GMT
< Access-Control-Allow-Credentials: true
< Transfer-Encoding: chunked
< Content-Type: multipart/related;start="<373c724d-9bcb-4587-985e-b8e564722765@resteasy-multipart>";transfer-syntax=1.2.840.10008.1.2.4.50;type="image/jpeg"; boundary=ee2160ef-4ed3-4ca2-879d-1acb1b0def0a
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
< 
{ [16392 bytes data]
* Connection #0 to host localhost left intact
```

**Comment by cgorman** [comment]
Ah yes sorry, I forgot to mention in my last comment that I was able to fix it with the q parameter, previously I had accidentally entered it within the text field, i.e. `"octet-stream;q=0.5"` instead of `"octet-stream"; q=0.5, but I think this change might be better off implemented in the dicomweb-client repository

**Comment by hackermd** [comment]
> @hackermd per discussion in the issue thread, I've updated the octet-stream mediatype to have a q-value weight of 0.5. Since this is just a part of the HTTP standard I don't imagine it will introduce issues, but let me know if you have any issues.

I don't see any issue with including the q parameter and agree that this should be implemented in dicomweb-client (probably [here](https://github.com/dcmjs-org/dicomweb-client/blob/7271467bb1dbe23e966eff50adc078a7bdae5552/src/api.js#L805-L807))

**Comment by cgorman** [comment]
Awesome, thanks for the link! I'll test it with a local build of slim and if it works i'll make a PR in that repo

**Pull request closed without merging**
