### PR TITLE
fix(viewer.js): Avoid rounding zoom factors that are too close to avoid duplicated resolution errors

### PR DESCRIPTION
**Pull request by igoroctaviano**
Address Error caused by rounding the zoom factor:: https://github.com/ImagingDataCommons/slim/issues/175

(level 0)
baseTotalPixelMatrixColumns / totalPixelMatrixColumns = 30920 / 30920 = 1
(level 1)
baseTotalPixelMatrixColumns / totalPixelMatrixColumns = 30920 / 1932 = 16.00414078674948 (16)
(level 2)
baseTotalPixelMatrixColumns / totalPixelMatrixColumns = 30920 / 1920 = 16.104166666666668 (16)

This way the resolutions array will be [16, 16, 1], and although its descending OpenLayers assertion doesn't allow equivalent numbers, the resolutions array should be composed of unique resolutions in descending order.

Removing the rounding here: https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/bda0cfea6f906a7c46f525cad2a5210d0722869b/src/pyramid.js#L211

Results:
Screenshot 2023-10-30 at 19 21 13

### CODE REVIEW

**Comment by fedorov** [comment]
@igoroctaviano following the discussion and review by @dclunie, let's hold this until we have a chance to review together.

**Comment by fedorov** [comment]
I agree with @dclunie we should fix this...

**Comment by fedorov** [comment]
I don't understand why we have these close resolution factors to begin with. I understand that's what was in the data converted, but why?

In principle, this proposed solution looks harmless to me. @dclunie what are your thoughts?

**Comment by dclunie** [comment]
Why? I suspect it is because of the area of tissue size (which varies), and the scanner vendor strategy of downsampling as many times as is necessary until some limit is reached, then also including a single layer that is the apex of the pyramid as a thumbnail, and sometimes these coincide fairly closely. But I am just speculating, and haven't examined this issue that closely.

**Review by fedorov — APPROVED** [review]

**Pull request merged**
