### PR TITLE
Update codecs version

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Update codecs version

### CODE REVIEW

**Comment by cgorman** [comment]
I took a crack at the failing tests. Jest needed to be upgraded to support package.json exports, but now it's giving a different error that [I can't figure out how to fix](https://www.sitepen.com/blog/jest-esm-almost-there).

**Comment by igoroctaviano** [comment]
@cgorman updated. Have you tested it locally with SLIM?

**Comment by cgorman** [comment]
> @cgorman updated. Have you tested it locally with SLIM?

@igoroctaviano Yup! Just did it again and it works mostly well. When running npm link in the slim repo I do get these errors

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @craco/craco@6.4.5
npm ERR! Found: react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   peer react-scripts@"^5.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     dev craco-less@"^2.0.0" from the root project
npm ERR!   dev react-scripts@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR! node_modules/@craco/craco
npm ERR!   peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     dev craco-less@"^2.0.0" from the root project
npm ERR!   dev @craco/craco@"^6.4.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-scripts@4.0.3
npm ERR! node_modules/react-scripts
npm ERR!   peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR!   node_modules/@craco/craco
npm ERR!     peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!       dev craco-less@"^2.0.0" from the root project
npm ERR!     dev @craco/craco@"^6.4.0" from the root project
npm ERR!
```

Is this something to fix in the slim repo or this one? Running link with `--force` works fine but I'm sure this will come up when I try to bump the dependency in slim. Other than that the decoding errors are fixed so we should be good to go!

**Comment by igoroctaviano** [comment]
> > @cgorman updated. Have you tested it locally with SLIM?
> 
> @igoroctaviano Yup! Just did it again and it works mostly well. When running npm link in the slim repo I do get these errors
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: @craco/craco@6.4.5
> npm ERR! Found: react-scripts@5.0.1
> npm ERR! node_modules/react-scripts
> npm ERR!   peer react-scripts@"^5.0.0" from craco-less@2.0.0
> npm ERR!   node_modules/craco-less
> npm ERR!     dev craco-less@"^2.0.0" from the root project
> npm ERR!   dev react-scripts@"^5.0.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
> npm ERR! node_modules/@craco/craco
> npm ERR!   peer @craco/craco@"^6.0.0" from craco-less@2.0.0
> npm ERR!   node_modules/craco-less
> npm ERR!     dev craco-less@"^2.0.0" from the root project
> npm ERR!   dev @craco/craco@"^6.4.0" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: react-scripts@4.0.3
> npm ERR! node_modules/react-scripts
> npm ERR!   peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
> npm ERR!   node_modules/@craco/craco
> npm ERR!     peer @craco/craco@"^6.0.0" from craco-less@2.0.0
> npm ERR!       dev craco-less@"^2.0.0" from the root project
> npm ERR!     dev @craco/craco@"^6.4.0" from the root project
> npm ERR!
> ```
> 
> Is this something to fix in the slim repo or this one? Running link with `--force` works fine but I'm sure this will come up when I try to bump the dependency in slim. Other than that the decoding errors are fixed so we should be good to go!

It happened after these changes or was like that before?

**Comment by cgorman** [comment]
> It happened after these changes or was like that before?

Oh good catch, yes I just tried with the master branch and it also happened so false alarm.

Do we need to commit the updated package-lock.json?

**Comment by igoroctaviano** [comment]
> > It happened after these changes or was like that before?
> 
> Oh good catch, yes I just tried with the master branch and it also happened so false alarm.
> 
> Do we need to commit the updated package-lock.json?

Yes, we need to update the lock to point to the newer versions.

**Comment by CPBridge** [comment]
No concerns from me. Thanks for the help @igoroctaviano!

**Review by CPBridge — APPROVED** [review]

**Comment by cgorman** [comment]
It seems I lack access to deploy github pages so we can't merge? @hackermd looks like you were the last person to do that successfully, could you lend a hand?

**Review by fedorov — APPROVED** [review]

**Comment by hackermd** [comment]
> It seems I lack access to deploy github pages so we can't merge? @hackermd looks like you were the last person to do that successfully, could you lend a hand?

I am not sure what is causing this issue. The deployment of gh-pages appeared to be successfully, so it's unclear why that blocked merging. For now, I have unchecked the deployment requirement in the branch protection rules.

Screen Shot 2023-05-27 at 10 23 32 AM

**Pull request merged**
