### PR TITLE
Fix/idc slim issue#84

### PR DESCRIPTION
**Pull request by rodrigobasilio2022**
This PR fixes the issue [#84](https://github.com/ImagingDataCommons/idc-slim/issues/84) related to open a monocromatic multichannel image

### CODE REVIEW

**Comment by fedorov** [comment]
@rodrigobasilio2022 why does this work for other images? It seems that if the array comparison function was wrong (1d vs 2d) it should have failed in other cases as well, no?

**Comment by rodrigobasilio2022** [comment]
@fedorov , No because it will only happens in monochromatic images like this. The color ones doesnt have the same checks

**Comment by fedorov** [comment]
@hackermd @CPBridge @cgorman would be great if you could review this!

**Comment by cgorman** [comment]
Looks good to me, thanks!

**Review by cgorman — APPROVED** [review]
Oops, meant to post that as a review. Looks good to me

**Pull request merged**
