### PR TITLE
Address annotation issues

### PR DESCRIPTION
**Pull request by igoroctaviano**
- When drawing measurements the first click was dragging the viewport instead of starting the drawing 
- When modifying the geometry the label and linked line was not having its coordinates updated (moving the label the annotation was anchored to the old geometry shape before it was modified)
- Addressed console errors caused by accessing optional values
- Update unit from array to codedConcept to avoid dcmjs errors

### CODE REVIEW

**Comment by fedorov** [comment]
> When drawing measurements the first click was dragging the viewport instead of starting the drawing

@cgorman @CPBridge - I thought Slim was used for creating annotations. How could such a bug slip through? Or is this some regression? Can you please take a look?

**Comment by cgorman** [comment]
Out of curiosity, what environment did you observe these issues? I haven't come across them myself but it could just be an OS and browser combo we haven't tested before.

**Comment by igoroctaviano** [comment]
> Out of curiosity, what environment did you observe these issues? I haven't come across them myself but it could just be an OS and browser combo we haven't tested before.

Well, nothing too special. I checked out to master branch + yarn start + chrome. Please let me know If you can't replicate this with your current config / environment so I can try yours and maybe identify this env specific issue.

**Comment by igoroctaviano** [comment]
@cgorman are you good with these changes? Have you had the chance to test it?

**Comment by igoroctaviano** [comment]
@CPBridge not sure if you noticed these problems too.

**Review by cgorman — APPROVED** [review]
Apologies, I meant to follow up on this and dropped the ball. I've confirmed tests pass and have tested locally with Slim, should be good to go.

**Pull request merged**
