### PR TITLE
fix(critical): isCoordinateInsideBoundingBox 

### PR DESCRIPTION
**Pull request by helmut-hoffer-von-ankershoffen**
isCoordinateInsideBoundingBox did not work for negative coordinates. now fixed, plus simplified.

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@helmut-hoffer-von-ankershoffen can you please address the build/unit test checks?

**Review by igoroctaviano — COMMENTED** [review]
LGTM, please address CI errors / lint

**Comment by helmut-hoffer-von-ankershoffen** [comment]
Sure, will do by EOW, just need to find a free minute,)

**Comment by helmut-hoffer-von-ankershoffen** [comment]
@igoroctaviano done

**Comment by igoroctaviano** [comment]
> @igoroctaviano done

Thank you!

**Review by igoroctaviano — APPROVED** [review]
🎖️

**Pull request merged**
